export const boroughs = {
  North: ["Barnet", "Camden", "Enfield", "Harringey", "Islington"],
  East: [
    "Barking and Dagenham",
    "Hackney",
    "Havering",
    "Newham",
    "Redbridge",
    "Tower Hamlets",
    "Waltham Forest",
  ],
  South: [
    "Bexley",
    "Bromley",
    "Croydon",
    "Greenwich",
    "Kingston upon Thames",
    "Lambeth",
    "Lewisham",
    "Merton",
    "Sutton",
    "Southwark",
    "Wandsworth",
  ],
  West: [
    "Brent",
    "Ealing",
    "Hammersmith and Fulham",
    "Harrow",
    "Hillingdon",
    "Hounslow",
    "Kensington and Chelsea",
    "Richmond upon Thames",
  ],
  Central: ["City of London", "Westminster"],
};
